// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr1fIRjDzCagwm6NpVBn2LN54SwZlB9ss',
    appId: '1:794964578447:web:2ef5b1ee210f5f2c46a0fa',
    messagingSenderId: '794964578447',
    projectId: 'sunmoney-5c1c1',
    authDomain: 'sunmoney-5c1c1.firebaseapp.com',
    databaseURL: 'https://sunmoney-5c1c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunmoney-5c1c1.firebasestorage.app',
    measurementId: 'G-J0HCTQXZL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB99kGiarg6k46Vn080SVQQ2QdvGHOrapM',
    appId: '1:794964578447:android:698c72b8ce326c1946a0fa',
    messagingSenderId: '794964578447',
    projectId: 'sunmoney-5c1c1',
    databaseURL: 'https://sunmoney-5c1c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunmoney-5c1c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuL8CDvsN08Z5y9AJJNyxWMnaxJitn80g',
    appId: '1:794964578447:ios:4caf2fa3ef3e280a46a0fa',
    messagingSenderId: '794964578447',
    projectId: 'sunmoney-5c1c1',
    databaseURL: 'https://sunmoney-5c1c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunmoney-5c1c1.firebasestorage.app',
    iosClientId: '794964578447-l7j4be9bs8hief22mdkrjttld12a1bb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneysun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuL8CDvsN08Z5y9AJJNyxWMnaxJitn80g',
    appId: '1:794964578447:ios:4caf2fa3ef3e280a46a0fa',
    messagingSenderId: '794964578447',
    projectId: 'sunmoney-5c1c1',
    databaseURL: 'https://sunmoney-5c1c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunmoney-5c1c1.firebasestorage.app',
    iosClientId: '794964578447-l7j4be9bs8hief22mdkrjttld12a1bb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneysun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr1fIRjDzCagwm6NpVBn2LN54SwZlB9ss',
    appId: '1:794964578447:web:83b39dd1d0ab75b346a0fa',
    messagingSenderId: '794964578447',
    projectId: 'sunmoney-5c1c1',
    authDomain: 'sunmoney-5c1c1.firebaseapp.com',
    databaseURL: 'https://sunmoney-5c1c1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sunmoney-5c1c1.firebasestorage.app',
    measurementId: 'G-P8NPCSY2J3',
  );
}
